services:
  directory-service:
    container_name: directory-service
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_TOKEN: ${NUGET_TOKEN}
    ports:
      - "8002:8002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8002
      - ConnectionStrings__DirectoryServiceDb=Server=postgres;Port=5432;Database=directory_service_db;User Id=postgres;Password=postgres;Search Path=public
      - Seq__ServerUrl=http://seq:5341
    depends_on:
      postgres:
        condition: service_healthy
      directory-service-migrations:
        condition: service_completed_successfully
    restart: always




  directory-service-migrations:
    container_name: directory-service-migrations
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_TOKEN: ${NUGET_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    entrypoint:
      [
        "/bin/sh",
        "-c",
        './efbundle --connection "Server=postgres;Port=5432;Database=directory_service_db;User Id=postgres;Password=postgres;Search Path=public"',
      ]

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d directory_service_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "8081:80"
      - "5341:5341"
    restart: always
    
    
volumes:
  postgres-data: