<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\FileService.Core\FileService.Core.csproj" />
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
    <ProjectReference Include="..\FileService.Infrastructure.Postgres\FileService.Infrastructure.Postgres.csproj" />
    <ProjectReference Include="..\FileService.Infrastructure.S3\FileService.Infrastructure.S3.csproj" />
  </ItemGroup>
</Project>
