<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>Wolonee.FileService.Client</PackageId>
      <Version>0.0.1</Version>
      <Authors>Wolonee</Authors>
      <Company>Wolonee</Company>
      <PackageDescription>Communication in FileService</PackageDescription>
      <RepositoryUrl>https://github.com/wolonee/DirectoryService</RepositoryUrl>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageReference Include="Wolonee.SharedKernel" Version="0.0.2" />
    <PackageReference Include="Wolonee.Core" Version="0.0.1" />
    <PackageReference Include="Wolonee.Framework" Version="0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FileService.Communications.UnitTests" />
  </ItemGroup>

</Project>
