<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>DirectoryService.FileService.Communication</PackageId>
      <Version>0.0.1</Version>
      <Authors>DirectoryService</Authors>
      <Company>DirectoryService</Company>
      <PackageDescription>Communication in FileService</PackageDescription>
      <RepositoryUrl>https://github.com/wolonee/DirectoryService</RepositoryUrl>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageReference Include="DirectoryService.SharedKernel" Version="0.0.2" />
    <PackageReference Include="DirectoryService.Core" Version="0.0.1" />
    <PackageReference Include="DirectoryService.Framework" Version="0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
  </ItemGroup>

</Project>
