<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>Wolonee.FileService.Contracts</PackageId>
      <Version>0.0.1</Version>
      <Authors>Wolonee</Authors>
      <Company>Wolonee</Company>
      <PackageDescription>Contracts in FileService</PackageDescription>
      <RepositoryUrl>https://github.com/wolonee/DirectoryService</RepositoryUrl>
    </PropertyGroup>

</Project>
