<Project Sdk="Microsoft.NET.Sdk">
  
    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    </ItemGroup>

  <PropertyGroup>
    <PackageId>Wolonee.SharedKernel</PackageId>
    <Version>0.0.2</Version>
    <Authors>Wolonee</Authors>
    <Company>Wolonee</Company>
    <PackageDescription>SharedKernel</PackageDescription>
    <RepositoryUrl>https://github.com/wolonee/DirectoryService</RepositoryUrl>
  </PropertyGroup>

</Project>
