<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FileService.Core\FileService.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.5" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.3" />
  </ItemGroup>
</Project>
