// <auto-generated />
using System;
using FileService.Infrastructure.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260812124340_RenameVideoProcessingRetryColumns")]
    partial class RenameVideoProcessingRetryColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.S3Entities.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalKey")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_key");

                    b.Property<string>("MultipartUploadId")
                        .HasColumnType("text")
                        .HasColumnName("multipart_upload_id");

                    b.Property<string>("RawKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage");

                    b.HasKey("Id");

                    b.HasIndex("FinalKey");

                    b.HasIndex("RawKey");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Usage", "Status");

                    b.ToTable("media_asset", "files");

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.S3Entities.MediaProcessing.VideoProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsCriticalError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("overall_progress_percentage");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_processing_status");

                    b.HasIndex("VideoAssetId")
                        .HasDatabaseName("ix_video_processing_video_asset_id");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_video_processing_status_started_at");

                    b.ToTable("video_processing", "files");
                });

            modelBuilder.Entity("FileService.Domain.S3Entities.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.S3Entities.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.S3Entities.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.S3Entities.Assets.MediaAsset");

                    b.Property<string>("HlsRootKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hls_root_key");

                    b.HasIndex("HlsRootKey");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.S3Entities.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.S3Entities.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("ExpectedChunksCount")
                                .HasColumnType("integer");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_asset", "files");

                            b1
                                .ToJson("media_data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.S3Entities.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_asset", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.S3Entities.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_asset", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.S3Entities.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.Property<Guid>("UploaderId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_uploader_id");

                            b1.HasKey("MediaAssetId");

                            b1.HasIndex("Context", "EntityId");

                            b1.ToTable("media_asset", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.S3Entities.StorageReference", "StorageReference", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .HasColumnType("text")
                                .HasColumnName("storage_reference_checksum");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_reference_content_type");

                            b1.Property<string>("ETag")
                                .HasColumnType("text")
                                .HasColumnName("storage_reference_etag");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("storage_reference_key");

                            b1.Property<DateTime?>("LastModified")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("storage_reference_last_modified");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("storage_reference_size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_asset", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("StorageReference");
                });

            modelBuilder.Entity("FileService.Domain.S3Entities.MediaProcessing.VideoProcess", b =>
                {
                    b.OwnsMany("FileService.Domain.S3Entities.MediaProcessing.ProcessingStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("step_type");

                            b1.Property<Guid>("VideoProcessingId")
                                .HasColumnType("uuid")
                                .HasColumnName("video_processing_id");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("weight");

                            b1.HasKey("Id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_processing_steps_status");

                            b1.HasIndex("StepType")
                                .HasDatabaseName("ix_processing_steps_step_type");

                            b1.HasIndex("VideoProcessingId");

                            b1.ToTable("processing_steps", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoProcessingId");
                        });

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
