// <auto-generated />
using System;
using FileService.Infrastructure.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260719152726_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_asset", "files");

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer")
                                .HasColumnName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_asset", "files");

                            b1
                                .ToJson("media_data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_asset", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_asset", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_asset", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
